### ISSUE TITLE
First Person Hands showing in 3rd Person View

### ISSUE THREAD

**Issue by Aaron1178** [DarkRisingStudios/SubZero#10]
The first person hands are showing in third person view and vice versa.

**Comment by fpwong** [comment]
Bug fixed in 1.1. Didn't notice this one since in game the meshes overlapped. Were they out of sync on your side?

**Comment by Aaron1178** [comment]
When you toggle to go to third person view, the First Person arms stay attached to the player but don't have any animation playing. When you go to First Person view and look straight down, you can see the bottom of the third person character, perhaps this is the intended effect ?

**Comment by fpwong** [comment]
Oh yea, I think I know what this is. I forgot to push it into my branch since it was in a different file.
I will make a pull request to fix this in 1.1 along with some other bugs but if you want to fix it you can add the line:

> ACharacter::Tick(DeltaSeconds);

to the top of the tick function in SubZeroCharacter.cpp

**Comment by Aaron1178** [comment]
Fixed in commit: 2a06458, by adding `ACharacter::Tick(DeltaSeconds);` to the tick method in SubZeroCharacter.cpp
